### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by amphilli** [harmslab/gpvolve#21]
<img width="598" alt="Screen Shot 2020-05-22 at 2 47 23 PM" src="https://user-images.githubusercontent.com/18492182/82699838-646ba080-9c3b-11ea-8133-ed7af3da5653.png">
<img width="1018" alt="Screen Shot 2020-05-22 at 2 46 37 PM" src="https://user-images.githubusercontent.com/18492182/82699839-65043700-9c3b-11ea-8921-2243dbba9141.png">

Unfortunately I haven't been able to get your examples to run:
https://gpvolve.readthedocs.io/en/latest/pages/pipeline.html
https://pypi.org/project/gpvolve/

To avoid dependency issues, I created a conda (v 4.8.2) virtual environment, installed pip (v 20.0.2), and installed gpvolve using pip. Then tried running the above examples in jupyter notebook. With both examples, I run into the same error:
ModuleNotFoundError: No module named 'gpvolve.cluster' (screenshot attached)
 
I also tried cloning the source code from GitHub and running that way (because I noticed the cluster directory in the source code, whereas it appears to be missing upon the pip install). But this throws a different error:
NameError: name 'flattened' is not defined (screenshot attached)

Which I also tried to fix by editing the source code (I think 'flattened' is a function in gpgraph.pyplot.pos)...but had no luck.

**Comment by lperezmo** [comment]
Hi @amphilli, thanks for the input, this problem has been fixed in the latest version 0.2.0 of gpvolve that was released recently. Feel free to check out our recently added example notebooks on nbviewer [nbviewer - Introduction to gpvolve](https://nbviewer.jupyter.org/github/harmslab/gpvolve/blob/master/examples/Introduction%20to%20gpvolve.ipynb). The notebooks should work without any problems on a local installation now. Binder is now ready too [Binder - Introduction to gpvolve](https://mybinder.org/v2/gh/harmslab/gpvolve.git/master?filepath=examples%2FIntroduction%20to%20gpvolve.ipynb)
